openapi: 3.0.1
info:
  title: '@jupiterone/graph-google-firebase'
  description: A JupiterOne Integration for ingesting data of the Google Firebase
  x-cortex-git:
    github:
      repository: JupiterOne/graph-google-firebase
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-google-firebase'
  x-cortex-service-groups:
    - tier-4
